#
# Copyright Jean-Charles Lambert, 2018-2019
#
# - YAML file for Continous Integration / Continous Deployement
# - unsio and python-unsio packages (RPM or DEB) are automatically
#   generated at new commit for different linux distribution
# - add manylinux building for python-module
#
# - Documentation :
#   https://docs.gitlab.com/ee/ci/yaml/

stages:
- build
# - sonar_scanner

variables :
  WHEEL       : 0
  OSX         : 0
  TEST         : 1
#  TESTPYPI    : 0
#  PYPI        : 0
#  TESTPYPIOSX : 0
#  PYPIOSX     : 0

#before_script:
  # clone
  #- git clone https://gitlab.lam.fr/vpicouet/DS9functions.git
  #- cd DS9functions


#
# BUILD wheels for all linux flavors/python
#



sonar_scanner:
  stage: build #sonar_scanner
  tags:
    - docker
  only:
    # - develop
    variables:
      - $TEST == "1"

  image: sonarsource/sonar-scanner-cli:latest
  script:
      - sonar-scanner \
        -Dsonar.projectKey=pyds9plugin \
        -Dsonar.sources=pyds9plugin \
        -Dsonar.host.url=https://sonarqube.lam.fr \
        -Dsonar.login=pyds9plugin
        # -Dsonar.python.coverage.reportPaths=report/coverage.xml
        # -Dsonar.python.xunit.reportPath=report/pytest.xml
        # -Dsonar.exclusions="src/svom_api_import/tests/*"
  allow_failure: true



manylinux2010 :
  stage : build
#  image : portus.lam.fr/jclamber/unsio-manylinux2010
  image : portus.lam.fr/vpicouet/pyds9quicklook-many-linux
  only :
    variables:
      - $WHEEL == "1"
  script:
    # build
    #- CI/script/build-DS9function.sh
    - CI/script/build-wheel.sh
    - /opt/python/cp37-cp37m/bin/python setup.py  bdist -d wheel
    #- CI/script/repair-wheel.sh
    #- /opt/python/cp37-cp37m/bin/python setup.py  sdist -d wheel
    #- CI/script/test-unsio.sh
  cache:
    key: manylinux2010
    paths:
      - dist/
  artifacts:
    name: "manylinux2010"
    paths:
#      - test-*.res
      - dist/*
    expire_in: 1 week



#
# BUILD wheels for macosx
#
OSX:
  stage : build
  tags:
    - osx_10.13.6
  only :
    variables:
      - $OSX == "1"
  script:
    # build
    - chmod +x CI/scriptOSX/build-wheel.sh
    - CI/scriptOSX/build-wheel.sh
  cache:
    key: osx
    paths:
      - dist/
  artifacts:
    name: "osx-wheel"
    paths:
      - dist/*
    expire_in: 1 week
